all:
	xelatex paper.tex
	bibtex paper
	xelatex paper.tex
	xelatex paper.tex
#	xelatex abstract.tex
###	bibtex abstract
#	xelatex abstract.tex
#	xelatex abstract.tex

clean:
	rm *.aux *.bbl *.blg *.log *.out
